version: "3.9"
services:
  seleniumtb:
    container_name: tb_watcher_selenium
    image: seleniarm/standalone-chromium:latest
    restart: always
    depends_on:
      - apptb
    volumes:
      - ./:/app
    env_file:
      - ./.env
    ports:
      - "4445:4444"

  apptb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tb_watcher_app
    stdin_open: true
    tty: true
    restart: always
    volumes:
      - ./app:/app
    env_file:
      - ./.env