[
    {
        "domain": ".taobao.com",
        "expirationDate": 1751354252,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_uetvid",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "09784c00333c11ee80419b5e7c9c483d"
    },
    {
        "domain": ".taobao.com",
        "expirationDate": 1725463124.187341,
        "hostOnly": false,
        "httpOnly": false,
        "name": "t",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "174064b713977fb0a288f531a3802b2e"
    },
    {
        "domain": ".taobao.com",
        "hostOnly": false,
        "httpOnly": false,
        "name": "existShop",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": true,
        "storeId": null,
        "value": "MTcxNzY1ODMyNw%3D%3D"
    },
    {
        "domain": ".taobao.com",
        "hostOnly": false,
        "httpOnly": true,
        "name": "cookie1",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": true,
        "storeId": null,
        "value": "VWgKlBNn57O3EEC%2BX91stZJ%2FxBImtkND5nt6QK4DEdA%3D"
    },
    {
        "domain": ".taobao.com",
        "expirationDate": 1717946324.187364,
        "hostOnly": false,
        "httpOnly": true,
        "name": "env_bak",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "FM%2BgndCFxXLztHtVsCmTO471p5uin7ZxkIpG479U94bk"
    },
    {
        "domain": ".taobao.com",
        "hostOnly": false,
        "httpOnly": false,
        "name": "csg",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": true,
        "storeId": null,
        "value": "9891817e"
    },
    {
        "domain": ".taobao.com",
        "expirationDate": 1722871124.187196,
        "hostOnly": false,
        "httpOnly": true,
        "name": "wk_cookie2",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "13a5bc41f75a24d3ef9165918b7cf7bc"
    },
    {
        "domain": ".taobao.com",
        "expirationDate": 1725175477,
        "hostOnly": false,
        "httpOnly": false,
        "name": "useNativeIM",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "false"
    },
    {
        "domain": ".taobao.com",
        "hostOnly": false,
        "httpOnly": true,
        "name": "cookie2",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": true,
        "storeId": null,
        "value": "238c0087425d3be3be129505ee521f09"
    },
    {
        "domain": ".taobao.com",
        "expirationDate": 1717917453,
        "hostOnly": false,
        "httpOnly": false,
        "name": "xlly_s",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "1"
    },
    {
        "domain": ".taobao.com",
        "hostOnly": false,
        "httpOnly": true,
        "name": "skt",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": true,
        "storeId": null,
        "value": "b8948d422fd0fdff"
    },
    {
        "domain": ".taobao.com",
        "expirationDate": 1717946324.187111,
        "hostOnly": false,
        "httpOnly": false,
        "name": "cookie3_bak_exp",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "1717917527842"
    },
    {
        "domain": ".taobao.com",
        "hostOnly": false,
        "httpOnly": true,
        "name": "unb",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": true,
        "storeId": null,
        "value": "2213284229025"
    },
    {
        "domain": ".taobao.com",
        "expirationDate": 1717946324.187086,
        "hostOnly": false,
        "httpOnly": true,
        "name": "cookie3_bak",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "238c0087425d3be3be129505ee521f09"
    },
    {
        "domain": ".taobao.com",
        "hostOnly": false,
        "httpOnly": false,
        "name": "_tb_token_",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": true,
        "storeId": null,
        "value": "3a1be9756ee5"
    },
    {
        "domain": ".taobao.com",
        "expirationDate": 1730253488.716512,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_ga",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "GA1.1.570942830.1691204344"
    },
    {
        "domain": ".taobao.com",
        "expirationDate": 1749223124.186997,
        "hostOnly": false,
        "httpOnly": true,
        "name": "sgcookie",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "E100uBVm909rLqhNngSYuE03SgIIjoFr9pWXaYaQMRD%2FAm19Snw53IEc%2FuWTtf6SJu1j7FXf7YgkiahrTsAkyVqNKJJf6P5aZstVmVkAmtKZg3bmNac4I60BfscDAyraJr53"
    },
    {
        "domain": ".taobao.com",
        "hostOnly": false,
        "httpOnly": true,
        "name": "_samesite_flag_",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": true,
        "storeId": null,
        "value": "true"
    },
    {
        "domain": ".taobao.com",
        "expirationDate": 1752218253.802126,
        "hostOnly": false,
        "httpOnly": false,
        "name": "cna",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "7kZjHqgDYGUCAQ6hG5cTKFYo"
    },
    {
        "domain": ".taobao.com",
        "expirationDate": 1733210334,
        "hostOnly": false,
        "httpOnly": false,
        "name": "tfstk",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "fpJIObjQ2y4QAAt1r6nNCEl5XVXWOeMqFusJm3eU29BKFgL25_ert955FFQwLw-FpYsJuF1Jza-UxCY2DJJEtTy5KTX-uqkq3DxhETd72JAl-hKG2OPAb5KHxTqgbzh26HVWzUuiATLRB1IlVTILe8n_WM7Tpged2Pn1qNQRe6I-BOI5VgQR9by3cgGC-HgPWK-IG0QkvNwXodsddWxd58yyCC1CkU7_e8p1AhvfTDejaZdc8s5BWAyCFhIW8N8xHR6OGIxPVeMQp9R9spXeQqaPOU_dad1sZ-56XpX9pIZ8eh6C-s9RTyg1kpx9nOCZHmt9Ie-HC3r-eG8VWHvdFxncd9QdCGvrSJQW6QpFtT4Ku6xJ1FsCHg-Y3Zi7x7Z1i8s1uci_Z7WQhPzgORlzS6IGA1osfydl9Gj6Xci_Zj5djGosfcNqi"
    },
    {
        "domain": ".taobao.com",
        "expirationDate": 1722871124.187214,
        "hostOnly": false,
        "httpOnly": true,
        "name": "wk_unb",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "UUpgRSoFgd3uSEAhbQ%3D%3D"
    },
    {
        "domain": ".taobao.com",
        "expirationDate": 1749223124.18752,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_cc_",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "UtASsssmfA%3D%3D"
    },
    {
        "domain": ".taobao.com",
        "expirationDate": 1722740374.059286,
        "hostOnly": false,
        "httpOnly": false,
        "name": "thw",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "xx"
    },
    {
        "domain": ".taobao.com",
        "expirationDate": 1717744652,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_uetsid",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "00e0c57023b111efbe6fffd9216db9e8"
    },
    {
        "domain": ".taobao.com",
        "expirationDate": 1717663652.503858,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_m_h5_tk_enc",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "b5c308b855cb9e467d272acac5a08ac4"
    },
    {
        "domain": ".taobao.com",
        "expirationDate": 1733210334,
        "hostOnly": false,
        "httpOnly": false,
        "name": "isg",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "BH19AMkix_1JIWCs95H4fb9kjNl3GrFsqrTGiT_CqVQDdp2oB25QPHSkJLIwdskk"
    },
    {
        "domain": ".taobao.com",
        "expirationDate": 1718551120.305691,
        "hostOnly": false,
        "httpOnly": false,
        "name": "3PcFlag",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "1717658324987"
    },
    {
        "domain": ".taobao.com",
        "expirationDate": 1730253555.762146,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_ga_JBTWV3NHSY",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "GS1.1.1695693488.18.1.1695693555.60.0.0"
    },
    {
        "domain": ".taobao.com",
        "expirationDate": 1730253555.16044,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_ga_YFVFB9JLVB",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "GS1.1.1695693488.18.1.1695693555.0.0.0"
    },
    {
        "domain": ".taobao.com",
        "expirationDate": 1725463124.18715,
        "hostOnly": false,
        "httpOnly": true,
        "name": "_hvn_lgc_",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "0"
    },
    {
        "domain": ".taobao.com",
        "hostOnly": false,
        "httpOnly": false,
        "name": "_l_g_",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": true,
        "storeId": null,
        "value": "Ug%3D%3D"
    },
    {
        "domain": ".taobao.com",
        "expirationDate": 1717663652.503832,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_m_h5_tk",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "123c6dee8491aef5681ab1e810b604fa_1717667976397"
    },
    {
        "domain": ".taobao.com",
        "hostOnly": false,
        "httpOnly": false,
        "name": "_nk_",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": true,
        "storeId": null,
        "value": "wuchengsg"
    },
    {
        "domain": ".taobao.com",
        "hostOnly": false,
        "httpOnly": false,
        "name": "cancelledSubSites",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": true,
        "storeId": null,
        "value": "empty"
    },
    {
        "domain": ".taobao.com",
        "hostOnly": false,
        "httpOnly": true,
        "name": "cookie17",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": true,
        "storeId": null,
        "value": "UUpgRSoFgd3uSEAhbQ%3D%3D"
    },
    {
        "domain": ".taobao.com",
        "expirationDate": 1720279124.187395,
        "hostOnly": false,
        "httpOnly": false,
        "name": "dnk",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "wuchengsg"
    },
    {
        "domain": ".taobao.com",
        "expirationDate": 1725463124.18713,
        "hostOnly": false,
        "httpOnly": true,
        "name": "havana_lgc2_0",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "eyJoaWQiOjIyMTMyODQyMjkwMjUsInNnIjoiYTBkYWFkZjc3M2YxYWQ4MTY4NTBiNGUyZDM3OWFkZWQiLCJzaXRlIjowLCJ0b2tlbiI6IjFHOXNRcFlxaVZlRzZwcF9NLUVqalJBIn0"
    },
    {
        "domain": ".taobao.com",
        "expirationDate": 1725463124.187169,
        "hostOnly": false,
        "httpOnly": false,
        "name": "havana_lgc_exp",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "1716844393263"
    },
    {
        "domain": ".taobao.com",
        "expirationDate": 1732125905.650163,
        "hostOnly": false,
        "httpOnly": false,
        "name": "hng",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "VN%7Czh-CN%7CVNM%7C704"
    },
    {
        "domain": ".taobao.com",
        "expirationDate": 1719992813,
        "hostOnly": false,
        "httpOnly": false,
        "name": "l",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "fBgw8dzlNeRYFXp_BO5alurza77T1KAjlsPzaNbMiIEGa1RRtBRGDNCOESsDSdtjQT5cyUKyQgQsVdEHSVaLRjkDBeYIi8nBhTO9VeM3N7AN."
    },
    {
        "domain": ".taobao.com",
        "expirationDate": 1720279124.187308,
        "hostOnly": false,
        "httpOnly": false,
        "name": "lgc",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "wuchengsg"
    },
    {
        "domain": ".taobao.com",
        "hostOnly": false,
        "httpOnly": false,
        "name": "sg",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": true,
        "storeId": null,
        "value": "g5f"
    },
    {
        "domain": ".taobao.com",
        "expirationDate": 1749223124.187483,
        "hostOnly": false,
        "httpOnly": false,
        "name": "tracknick",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "wuchengsg"
    },
    {
        "domain": ".taobao.com",
        "hostOnly": false,
        "httpOnly": false,
        "name": "uc1",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": true,
        "storeId": null,
        "value": "existShop=false&cookie16=V32FPkk%2FxXMk5UvIbNtImtMfJQ%3D%3D&cookie14=UoYfpueuVANUUw%3D%3D&cookie21=URm48syIYB3rzvI4Dim4&pas=0&cookie15=VT5L2FSpMGV7TQ%3D%3D"
    },
    {
        "domain": ".taobao.com",
        "expirationDate": 1720279124.187278,
        "hostOnly": false,
        "httpOnly": true,
        "name": "uc3",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "nk2=FOxvsth9uJcY&vt3=F8dD3iz2pWqWiOCCZQQ%3D&id2=UUpgRSoFgd3uSEAhbQ%3D%3D&lg2=U%2BGCWk%2F75gdr5Q%3D%3D"
    },
    {
        "domain": ".taobao.com",
        "expirationDate": 1720279124.187455,
        "hostOnly": false,
        "httpOnly": true,
        "name": "uc4",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "nk4=0%40FmduSMsm00sxeN24BHkv5GMOiW8%3D&id4=0%40U2gqykLs3ak%2FW%2BNoLo4ksmCyZnuuGSiq"
    }
]